# Generated by Django 4.1.1 on 2022-09-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foot',
            name='price_day',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='housing',
            name='price',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='location',
            name='distance_air',
            field=models.CharField(max_length=200),
        ),
    ]
