# Generated by Django 4.1.1 on 2022-09-06 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turist', '0002_alter_foot_price_day_alter_housing_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=100)),
                ('telegram', models.CharField(max_length=100)),
                ('home', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='foot',
            name='kitchen',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='foot',
            name='price_day',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='housing',
            name='pic_cart',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='price',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='location',
            name='picture',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AddField(
            model_name='housing',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='turist.contact'),
            preserve_default=False,
        ),
    ]
