# Generated by Django 4.1.1 on 2022-09-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turist', '0003_contact_alter_foot_kitchen_alter_foot_price_day_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foot',
            new_name='Food',
        ),
    ]
