# Generated by Django 4.1.1 on 2022-09-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turist', '0006_route_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='picture',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housing',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kind_transport',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='picture',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
    ]
